---
- name: Install NTP Ubuntu
  apt:
    name: chrony
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start NTP
  service:
    name: chronyd
    state: restarted
    enabled: true

- name: Install OpenStack packages
  apt:
    name: python3-openstackclient
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install SQL Database 
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start SQL Database
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: Install Message Queue
  apt:
    name: rabbitmq-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start Message Queue
  service:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: Install Memcached
  apt:
    name: memcached
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start Memcached
  service:
    name: memcached
    state: restarted
    enabled: true

- name: Install Etcd
  apt:
    name: etcd-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start Etcd
  service:
    name: etcd
    state: restarted
    enabled: true
